
# 모듈
## 모듈이란
> 모듈은 프로그램을 구성하는 구성 요소의 일부를 말함. <br/>
> JavaScript에서 모듈은 하나의 .js 스크립트를 말함.

JavaScript에서 하나의 스크립트의 크기가 점차 커지고 기능이 복잡해짐에 따라, 라이브러리를 만들어 필요한 모듈을 불러오거나, 모듈로 쉽게 분리할 수 있는 방법을 제시하게 됨.

## 모듈 시스템
- AMD : 가장 오래된 모듈 시스템 중 하나. `require.js`라는 라이브러리를 통해 처음 개발.
- CommonJS: node.sj 서버를 위해 만들어짐. node.js 에서 사용한다.
- UMD: AMD와 CommonJS와 같은 모듈 시스템을 함께 사용하기 위해 등장.

### CommonJS 방식
`module.exports`, `exports`를 사용해 모듈을 해당 스코프 밖으로 보낼 수 있음.
`require`를 사용해 외부 모듈의 기능을 가져옴.
```javascript
// a.js
const printHelloWorld = () => {
	console.log("Hello World");
};
module.exports = {
	printHelloWorld
};

exports.add = function(a, b) {
	return a + b;
}

// b.js
const func = require('.a/js');
func.printHelloWorld();
```

### ES6 방식
`export` 지시자를 변수나 함수 앞에 붙이면 외부 모듈에서 해당 변수나 함수에 접근할 수 있음.
`import` 지시자를 사용하여 외부 모듈의 기능을 가져올 수 있음.
```javascript
// sayHi.js
export function sayHi (user) {
	console.log(`Hello, ${user}!`);
}

// main.js
import { sayHi } from "./sayHi.js";
sayHi('John'); // Hello, John!
```

모듈은 특수한 키워드나 기능과 함께 사용되므로, `<script type="module">` 같은 속성을 설정해, 해당 스크립트가 모듈이라는 것을 브라우저에 알려야 함.
```html
<!doctype html>
<script type="module">
	import { sayHi } from "./sayHi.js";
	document.body.innerHTML = sayHi("John");
</script>
```

<br/>

## 모듈의 기능
### 엄격 모드로 실행됨
모듈은 항상 "엄격 모드(use strict)"로 실행됨.
선언되지 않은 변수에 값을 할당하는 등의 코드는 에러 발생.
반드시 `export`와 `import`를 사용해야 한다.
```html
<script type="module">
	a = 5; // 에러
</script>
```

### 모듈 레벨 스코프
모듈은 해당 모듈만의 스코프가 있으며, 모듈 내부에서 정의한 변수나 함수는 다른 스크립트에서 접근할 수 없음.
```javascript
// user.js
let user = "John";
// hello.js
console.log(user); // error
```

 전역 변수를 대신해 `hello.js`에 `user.js`를 가져와 필요한 기능을 얻을 수 있음.
```javascript
// user.js
export let user = "John";
// hello.js
import { user } from "./user.js";
console.log(user); // John
```

### 단 한 번만 평가됨
동일한 모듈이 여러 곳에서 사용되더라도, **모듈은 최초 호출 시 단 한 번만 실행됨.**
실행 후 결과는 이 모듈을 import 하는 모든 모듈에 export 됨.
최상위 레벨 모듈을 **초기화**나, **내부에서 쓰이는 데이터 구조를 만들고 이를 내보내 재사용**하고 싶을 때 사용할 수 있음.
```javascript
// alert.js
console.log("모듈이 평가되었습니다.");

// 동일한 모듈을 여러 모듈에서 가져옴.
// 1.js
import './alert.js' // 모듈이 평가되었습니다. (console 출력)
// 2.js
import './alert.js' // 아무 일도 발생하지 않음.
```

```javascript
// admin.js
export let admin = {
	name: "John"
};
```
- `admin` 모듈을 가져오는 모듈이 여러 개이더라도, 모듈은 최초 호출 시 단 한 번만 평가됨.
- `admin` 객체가 만들어지고, 이 모듈을 import 하는 모든 모듈에 동일한 `admin` 객체가 전달됨.

```javascript
// 1.js
import { admin } from "./admin.js";
admin.name = 'Pete';

// 2.js
import { admin } from "./admin.js";
console.log(admin.name); // Pete
```
- `1.js`와 `2.js` 모두 같은 객체를 가져오므로, `1.js`에서 객체에 가한 조작을 `2.js`에서 확인할 수 있음.

<br/>

## 모듈의 장점
- 유지보수성 : 모듈화가 잘 되어있다면, 의존성이 줄기 때문에 유지보수성이 개선됨.
- 네임스페이스화 : 자바스크렙트에서 전역변수는 전역공간을 갖기 때문에, 코드의 양이 많아질수록 겹치는 네임스페이스가 많아질 수 있음. 모듈로 분리하면 모듈만의 네임스페이스를 갖기 때문에 문제가 해결됨.
- 재사용성 : 똑같은 코드를 반복하지 않고 모듈로 분리하여, 필요할 때마다 사용할 수 있음.

<br/>

---

<br/>

# 에러 

`Error` 객체는 런타임 오류가 발생했을 때 던져짐.

## 에러의 유형

| 유형            | 내용                                                         |
| --------------- | ------------------------------------------------------------ |
| Syntax Error    | `eval()`이 코드를 분석하는 중 잘못된 구문을 만났을 때 발생하는 오류. |
| TypeError       | 변수나 매개변수가 유효한 자료형이 아님을 나타내는 오류.      |
| EvalError       | 전역 함수 `eval()`에서 발생하는 오류.                        |
| RangeError      | 숫자 변수나 매개변수가 유효한 범위를 벗어났을 때 발생하는 오류. |
| Reference Error | 잘못된 참조를 했을 때 나타나는 오류.                         |
| URIError        | `encodeURI()`나 `decodeURI()` 부적절한 매개변수를 제공했을 때 발생하는 오류. |
| AggregateError  | 하나의 동작이 여러 개의 오류를 발생시키는 경우, 여러 오류를 하나의 오류로 감싸는 인스턴스. |


## 에러 발생

`Error` 객체를 생성한 후에 `throw` 키워드를 이용하여 발생시킴.
`try/catch` 구문을 이용해 오류를 처리할 수 있다.

```javascript
try {
	throw new Error("에러 발생");
} catch(e) {
	console.log(`${e.name}: ${e.message}`)
}
```

<br/>

# 예외 처리

예외 처리(exception handling) : 에러가 발생했을 때, 코드의 실행 흐름을 복구할 수 있도록 하는 기능.

## 동기식 코드에서의 예외 처리

코드 실행 중 에러가 발생하면, 코드의 실행이 중단되어 그 시점에 실행 중이었던 작업을 완료할 수 없음.
`try/catch` 구문을 이용하여, 코드의 실행을 지속할 수 있음.

### try/catch/finally

```javascript
try {
	console.log("에러 발생 전");
	new Array(-1); // RangeError: Invalid array length
	console.log("에러 발생 후 코드 실행되지 않음.");
} catch (e) {
	console.log("코드 실행 흐름이 catch 블록으로 옮겨짐.");
	console.log(`에러 발생: ${e.name}: ${e.message} `);
} finally {
	console.log("에러 발생 여부와 관계 없이 실행됨.")
}
```

## 비동기식 코드에서의 예외 처리

### 비동기 콜백

비동기식으로 작동하는 콜백의 내부에서 발생한 에러는, 콜백 바깥에 있는 `try` 블록으로 잡아낼 수 없음.

```javascript
try {
	setTimeout(()=>{
		throw new Error("에러!");
	});
} catch (e) {
	console.log(e);
}
```

- JavaScript 엔진이 에러를 발생하여 콜 스택 을 되감는 과정에서, `try` 블록을 만나야 실행 흐름을 원상복구 할 수 있음.
- `setTimeout`에 넘겨진 콜백에서 에러가 발생하면, 콜 스택을 따라 올라가도 `try` 블록을 만날 수 없기 때문에 코드의 실행 흐름이 `catch` 블록으로 넘어가지 않는다.
- 따라서 `try` 블록을 비동기 콜백 내부에 작성해야 함.

```javascript
setTimeout(()=>{
	try {
		throw new Error("에러!");
	} catch (e) {
		console.log(e);
	}
})
```

### Promise

Promise 객체의 상태가 `rejected`가 되면,

- `then` 메소드에 첫 번째 인수로 넘겨준 콜백이 실행되지 않고, **두 번째 인수로 넘겨준 콜백이 실행**됨.
- 해당 콜백에는 **에러 객체가 첫 번째 인수로** 주어짐.

```javascript
const p = new Promise(resolve => {
	const even = parseInt(prompt('짝수를 입력하세요.: '));
	if (even % 2 != 0) throw new Error ("짝수가 아닙니다.");
	else resolve(even);
})

p.then(even => {
	return "짝수입니다.";
}, e => {
	return e.message;
}).then(alert);
```

`catch` 블록을 이용할 수 있다.

```javascript
p.then(even => {
	return "짝수입니다.";
}).catch(e => {
	return e.message;
}).then(alert);
```

### 비동기 함수

비동기 함수 내부에서 `rejected` 상태가 된 Promise 객체를 `try/catch/finally` 구문으로 처리할 수 있다.

```javascript
async function func() {
	try {
		const res = await fetch("https://nonexistent-domain.nowhere");
	} catch (e) {
		console.log(e.message);
	}
}
func(); // 출력 결과: Failed to fetch
```


---

**Reference**

[모듈 소개](https://ko.javascript.info/modules-intro#ref-338)

[[JavaScript] 모듈이란?](https://80000coding.oopy.io/a9e13d5e-e858-40f5-a80f-dbb50d0b65f4)

[[JS] 모듈에 대한 이해와 사용법](https://baeharam.netlify.app/posts/javascript/module)

[예외 처리](https://helloworldjavascript.net/pages/290-exception.html#%EB%B9%84%EB%8F%99%EA%B8%B0%EC%8B%9D-%EC%BD%94%EB%93%9C%EC%97%90%EC%84%9C%EC%9D%98-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)

[Error](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error)
